In [36]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [37]:
data= pd.read_csv("/content/Telco-CustomerChurn_Uncleaned.csv")
data.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,4597-NUCQV,Male,1,No,No,24,Yes,Yes,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,101.25,2440.15,Yes
1,9426-SXNHE,Female,0,No,No,2,Yes,No,NaN,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Bank transfer (automatic),18.75,53.15,No
2,2379-GYFLQ,Male,0,No,No,46,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,No,1 Year,Yes,Credit card (automatic),94.90,4422.95,No
3,3506-LCJDC,Male,0,Yes,Yes,1,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Bank transfer (automatic),19.95,19.95,Yes
4,4374-YMUSQ,Male,0,No,No,34,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,One year,No,Credit card (automatic),116.25,3899.05,No

In [38]:
data.shape

(7143, 21)

In [39]:
print(data.describe())
print('---'*20)
data.info()

       SeniorCitizen  tenure  MonthlyCharges
count        7143.00 7143.00         7082.00
mean            0.16   32.37           64.50
std             0.37   24.56           30.50
min             0.00    0.00         -117.50
25%             0.00    9.00           35.16
50%             0.00   29.00           70.25
75%             0.00   55.00           89.85
max             1.00   72.00          118.75
------------------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7143 entries, 0 to 7142
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7143 non-null   object
 1   gender            7063 non-null   object
 2   SeniorCitizen     7143 non-null   int64
 3   Partner           7143 non-null   object
 4   Dependents        7143 non-null   object
 5   tenure            7143 non-null   int64
 6   PhoneService      7143 non-null   object
 7   MultipleLines     7143 non-null   object
 8   InternetService   7072 non-null   object
 9   OnlineSecurity    7143 non-null   object
 10  OnlineBackup      7143 non-null   object
 11  DeviceProtection  7143 non-null   object
 12  TechSupport       7143 non-null   object
 13  StreamingTV       7143 non-null   object
 14  StreamingMovies   7143 non-null   object
 15  Contract          7092 non-null   object
 16  PaperlessBilling  7143 non-null   object
 17  PaymentMethod     7073 non-null   object
 18  MonthlyCharges    7082 non-null   float64
 19  TotalCharges      7052 non-null   object
 20  Churn             7143 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [40]:
data.isnull()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7138,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7139,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7140,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7141,False,True,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,True,False,False,False
7142,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [41]:
data.isnull().sum()

customerID           0
gender              80
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService     71
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract            51
PaperlessBilling     0
PaymentMethod       70
MonthlyCharges      61
TotalCharges        91
Churn                0
dtype: int64